# Generated by Django 3.0.6 on 2021-02-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userType',
            field=models.IntegerField(choices=[(1, 'User'), (2, 'Commercial')], default=1),
        ),
    ]
